### PR TITLE
Added support to self-hosted gitlab and list of modules

### PR DESCRIPTION
**Pull request by Kell0x**
Hello, I worked a little on your tool for a personal usage and I thought it would be great if anyone could use what I made too :)

### CODE REVIEW

**Comment by ri0tsec** [comment]
Sweet thats awesome! I love ptf, and It makes my job much less tedious. 

> Hello, I worked a little on your tool for a personal usage and I thought it would be great if anyone could use what I made too :)

**Comment by trustedsec** [comment]
Hey there! Cool stuff and great idea on the gitlab. 

I'm trying to figure out the listes component, what exactly are you trying to do here? When I run it I just get a update all prompt:

ptf> use modules/listes/list
[*] You are about to install/update everything. Proceed? [yes/no]:no

**Comment by trustedsec** [comment]
Ahhh, I see - a way for you to build a list of modules you want to install. That makes sense. Thanks this is great.

**Comment by trustedsec** [comment]
Just an FYI, I changed "listes" to "custom_list" - easier to describe I think in that one. Thanks for the contributions. This is great!

**Comment by Kell0x** [comment]
Thank you, hope it will be useful :)

**Pull request merged**
