### PR TITLE
resolved dirb issues and fixed fluxion module

### PR DESCRIPTION
**Pull request by BustedSec**

### CODE REVIEW

**Comment by trustedsec** [comment]
There's a lot more to this one than fixing a few things. Looks like it also adds a perl script and some more. I don't want to add perl modules to a Python-based platform. Would need to investigate and go through this more... I do appreciate it, and there's a lot of great stuff in here. Just need to investigate this more.

**Comment by BustedSec** [comment]
I took that perl script out - and also took out the user-submited module section I had made - if you look at the last few commits - I needed to bring my fork up to date with master and the only way I could do it without deleting it was to merge the two and remove my changes I made to my fork.

**Comment by BustedSec** [comment]
if you're more comfortable, you could just take the fixes to the dirb and fluxion modules and incorporate those rather than pulling my copy

**Comment by trustedsec** [comment]
On vacation right now btw. Will take a peek at this on Monday :)

**Comment by BustedSec** [comment]
enjoy your vacation dave!

**Comment by BustedSec** [comment]
gonna kill this pull request. Need to make a few more changes. In framwork.py I'm going to change line 431 and 432 around. This fix was proposed by another user in a bug report and I made the changes locally and confirmed it fixes issues with the dirb installer.

**Pull request closed without merging**
