### PR TITLE
Various dep and launcher fixes

### PR DESCRIPTION
**Pull request by bricethegrey**
Updated various xUbuntu/debian dependencies based on a clean install, as well as a few after_command/launcher issues.

### CODE REVIEW

**Comment by trustedsec** [comment]
Appreciate the changes, these are great additions and fixes. Can you fix the launchers ? No launcher should have an extension of .py, .pl, etc. it'll automatically pull those and add them so theres no need to put those there. 

Also for yersinia, its removing the build for that:

yersinia -> -AFTER_COMMANDS="cd {INSTALL_LOCATION},./configure,make,make install"

Probably shouldn't remove that so it doesn't remove it.

**Comment by bricethegrey** [comment]
Will do.

**Comment by bricethegrey** [comment]
Done.  My bad for yersinia.  I was having trouble with the repository on this one.  It's now the original.

**Comment by trustedsec** [comment]
This looks great, thanks for going through and fixing these.

**Comment by bewithsahilsaif** [comment]
``[](# [url)``](">

**Comment by bewithsahilsaif** [comment]
Awesome

**Pull request merged**
